$(function() {
    $(document).ready(function() {
    $('#year').on('change',checkSumm);
    $('#year_made').on('change',checkSumm);
    $('#type_avto').on('change',checkSumm);
    $('#volume').on('change',checkSumm);
    $('#type_plat').on('change',checkSumm);
    });

    function checkSumm()
    {
        var year=$('#year').val();
        var year_made=$('#year_made').val();
        var type_avto=$('#type_avto option:selected').val();
        var volume=$('#volume').val();
        var type_plat=$('#type_plat option:selected').val();
        console.log(type_avto);
        console.log(type_plat);
        var old=year-year_made;
         console.log(old);
        var stavka=1;
        if(type_avto==1){
            if(type_plat==1){
                if(old<5)
                {
                  stavka=5;
                }
                if(old>=5&&old<10)
                {
                    stavka=4;
                }
                if(old>=10&&old<15)
                {
                    stavka=3.5;
                }
                if(old>=15&&old<20)
                {
                    stavka=3;
                }
                if(old>=20)
                {
                    stavka=2.5;
                }
            }
            else
            {
                stavka=2.5;
            }
        }
        if(type_avto==2){
            if(type_plat==1){
                if(old<5)
                {
                  stavka=30;
                }
                if(old>=5&&old<10)
                {
                    stavka=24;
                }
                if(old>=10&&old<15)
                {
                    stavka=21;
                }
                if(old>=15&&old<20)
                {
                    stavka=18;
                }
                if(old>=20)
                {
                    stavka=15;
                }
            }
            else
            {
                stavka=15;
            }
        }
        if(type_avto==3){
            if(type_plat==1){
                if(old<5)
                {
                  stavka=10;
                }
                if(old>=5&&old<10)
                {
                    stavka=8;
                }
                if(old>=10&&old<15)
                {
                    stavka=7;
                }
                if(old>=15&&old<20)
                {
                    stavka=6;
                }
                if(old>=20)
                {
                    stavka=5;
                }
            }
            else
            {
                stavka=5;
            }
        }
        if(type_avto==4){
            if(volume<=1000){
                if(type_plat==1){
                    if(old<5)
                    {
                      stavka=6;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=4.8;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=4.2;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=3.6;
                    }
                    if(old>=20)
                    {
                        stavka=3;
                    }
                }
                else
                {
                    stavka=3;
                }
            }
            if(volume>1000&&volume<=1500){
                if(type_plat==1){
                    if(old<5)
                    {
                      stavka=10;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=8;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=7;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=6;
                    }
                    if(old>=20)
                    {
                        stavka=5;
                    }
                }
                else
                {
                    stavka=5;
                }
            }
            if(volume>1500&&volume<=1800){
                if(type_plat==1){
                    if(old<5)
                    {
                      stavka=14;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=11.2;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=9.8;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=8.4;
                    }
                    if(old>=20)
                    {
                        stavka=7;
                    }
                }
                else
                {
                    stavka=7;
                }
            }
                if(volume>1800&&volume<=2500){
                    if(type_plat==1){
                    if(old<5)
                    {
                      stavka=20;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=16;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=14;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=12;
                    }
                    if(old>=20)
                    {
                        stavka=10;
                    }
                }
                else
                {
                    stavka=10;
                }
            }
                if(volume>2500&&volume<=3500){
                if(type_plat==1){
                    if(old<5)
                    {
                      stavka=50;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=40;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=35;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=30;
                    }
                    if(old>=20)
                    {
                        stavka=25;
                    }
                }
                else
                {
                    stavka=25;
                }
            }
            if(volume>3500){
                if(type_plat==1){
                    if(old<5)
                    {
                      stavka=80;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=64;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=56;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=48;
                    }
                    if(old>=20)
                    {
                        stavka=40;
                    }
                }
                else
                {
                    stavka=40;
                }
            }
        }
        if(type_avto==5){
            if(type_plat==1){
                if(old<5)
                {
                  stavka=10;
                }
                if(old>=5&&old<10)
                {
                    stavka=8;
                }
                if(old>=10&&old<15)
                {
                    stavka=7;
                }
                if(old>=15&&old<20)
                {
                    stavka=6;
                }
                if(old>=20)
                {
                    stavka=5;
                }
            }
            else
            {
                stavka=5;
            }
        }
        if(type_avto==6){
            if(volume<=8200){
                if(type_plat==1){
                    if(old<5)
                    {
                      stavka=30;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=24;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=21;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=18;
                    }
                    if(old>=20)
                    {
                        stavka=15;
                    }
                }
                else
                {
                    stavka=15;
                }
            }
            if(volume>8200&&volume<=15000){
                if(type_plat==1){
                    if(old<5)
                    {
                      stavka=40;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=32;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=28;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=24;
                    }
                    if(old>=20)
                    {
                        stavka=20;
                    }
                }
                else
                {
                    stavka=20;
                }
            }
            if(volume>15000){
                if(type_plat==1){
                    if(old<5)
                    {
                      stavka=50;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=40;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=35;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=30;
                    }
                    if(old>=20)
                    {
                        stavka=25;
                    }
                }
                else
                {
                    stavka=25;
                }
            }

        }
        if(type_avto==7){
            if(type_plat==1){
                if(old<5)
                {
                  stavka=10;
                }
                if(old>=5&&old<10)
                {
                    stavka=8;
                }
                if(old>=10&&old<15)
                {
                    stavka=7;
                }
                if(old>=15&&old<20)
                {
                    stavka=6;
                }
                if(old>=20)
                {
                    stavka=5;
                }
            }
            else
            {
                stavka=5;
            }
        }
        if(type_avto==8){
            if(volume<=500){
                if(type_plat==1){
                    if(old<5)
                    {
                      stavka=6;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=4.8;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=4.2;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=3.6;
                    }
                    if(old>=20)
                    {
                        stavka=3;
                    }
                }
                else
                {
                    stavka=3;
                }
            }
            if(volume>500&&volume<=800){
                if(type_plat==1){
                    if(old<5)
                    {
                      stavka=10;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=8;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=7;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=6;
                    }
                    if(old>=20)
                    {
                        stavka=5;
                    }
                }
                else
                {
                    stavka=5;
                }
            }
            if(volume>800){
                if(type_plat==1){
                    if(old<=5)
                    {
                      stavka=20;
                    }
                    if(old>=5&&old<10)
                    {
                        stavka=16;
                    }
                    if(old>=10&&old<15)
                    {
                        stavka=14;
                    }
                    if(old>=15&&old<20)
                    {
                        stavka=12;
                    }
                    if(old>=20)
                    {
                        stavka=10;
                    }
                }
                else
                {
                    stavka=10;
                }
            }

        }
        if(type_avto==91){
            if(type_plat==1){
                if(old<=5)
                {
                  stavka=28;
                }
                if(old>=5&&old<10)
                {
                    stavka=22.4;
                }
                if(old>=10&&old<15)
                {
                    stavka=19.6;
                }
                if(old>=15&&old<20)
                {
                    stavka=16.8;
                }
                if(old>=20)
                {
                    stavka=14;
                }
            } else
            {
                stavka=14;
            }
        }
        if(type_avto==92){
            if(type_plat==1){
            if(old<=5)
                {
                  stavka=14;
                }
                if(old>=5&&old<10)
                {
                    stavka=11.2;
                }
                if(old>=10&&old<15)
                {
                    stavka=9.8;
                }
                if(old>=15&&old<20)
                {
                    stavka=8.4;
                }
                if(old>=20)
                {
                    stavka=7;
                }
            } else
            {
                stavka=7;
            }
        }
        if(type_avto==93){
            if(type_plat==1){
            if(old<=5)
                {
                  stavka=14;
                }
                if(old>=5&&old<10)
                {
                    stavka=11.2;
                }
                if(old>=10&&old<15)
                {
                    stavka=9.8;
                }
                if(old>=15&&old<20)
                {
                    stavka=8.4;
                }
                if(old>=20)
                {
                    stavka=7;
                }
            } else
            {
                stavka=7;
            }
        }
        if(type_avto==94){
            if(type_plat==1){
            if(old<=5)
                {
                  stavka=28;
                }
                if(old>=5&&old<10)
                {
                    stavka=22.4;
                }
                if(old>=10&&old<15)
                {
                    stavka=19.6;
                }
                if(old>=15&&old<20)
                {
                    stavka=16.8;
                }
                if(old>=20)
                {
                    stavka=14;
                }
            } else
            {
                stavka=14;
            }
        }
        if(type_avto==101){
            if(type_plat==1){
            if(old<=5)
                {
                  stavka=28;
                }
                if(old>=5&&old<10)
                {
                    stavka=22.4;
                }
                if(old>=10&&old<15)
                {
                    stavka=19.6;
                }
                if(old>=15&&old<20)
                {
                    stavka=16.8;
                }
                if(old>=20)
                {
                    stavka=14;
                }
            } else
            {
                stavka=14;
            }
        }
        if(type_avto==102){
           if(type_plat==1){
            if(old<=5)
                {
                  stavka=14;
                }
                if(old>=5&&old<10)
                {
                    stavka=11.2;
                }
                if(old>=10&&old<15)
                {
                    stavka=9.8;
                }
                if(old>=15&&old<20)
                {
                    stavka=8.4;
                }
                if(old>=20)
                {
                    stavka=7;
                }
            } else
            {
                stavka=7;
            }
        }
        if(type_avto==103){
           if(type_plat==1){
            if(old<=5)
                {
                  stavka=28;
                }
                if(old>=5&&old<10)
                {
                    stavka=22.4;
                }
                if(old>=10&&old<15)
                {
                    stavka=19.6;
                }
                if(old>=15&&old<20)
                {
                    stavka=16.8;
                }
                if(old>=20)
                {
                    stavka=14;
                }
            } else
            {
                stavka=14;
            }
        }
        if(type_avto==111){
            if(type_plat==1){
            if(old<=5)
                {
                  stavka=14;
                }
                if(old>=5&&old<10)
                {
                    stavka=11.2;
                }
                if(old>=10&&old<15)
                {
                    stavka=9.8;
                }
                if(old>=15&&old<20)
                {
                    stavka=8.4;
                }
                if(old>=20)
                {
                    stavka=7;
                }
            } else
            {
                stavka=7;
            }
        }
        if(type_avto==112){
            if(type_plat==1){
            if(old<=5)
                {
                  stavka=14;
                }
                if(old>=5&&old<10)
                {
                    stavka=11.2;
                }
                if(old>=10&&old<15)
                {
                    stavka=9.8;
                }
                if(old>=15&&old<20)
                {
                    stavka=8.4;
                }
                if(old>=20)
                {
                    stavka=7;
                }
            } else
            {
                stavka=7;
            }
        }
        if(type_avto==113){
            if(type_plat==1){
            if(old<=5)
                {
                  stavka=28;
                }
                if(old>=5&&old<10)
                {
                    stavka=22.4;
                }
                if(old>=10&&old<15)
                {
                    stavka=19.6;
                }
                if(old>=15&&old<20)
                {
                    stavka=16.8;
                }
                if(old>=20)
                {
                    stavka=14;
                }
            } else
            {
                stavka=14;
            }
        }
        console.log(stavka);
        var sum=(volume/100)*stavka;
       sum.toFixed(2);
        console.log(sum.toFixed(2));
        $('#summa').val(sum.toFixed(2));
    }
});
